export const EVENT_SOURCES = [
    `https://www.czechstartups.org/akce/`,
    `https://www.eventbrite.com/o/wrike-tech-club-27552199725`,
    `https://it.katalogakci.cz/`,
    `https://www.wug.cz/`,
    `https://www.openalt.org/`,
    `https://www.meetup.com/Prague-AWS-Meetup/`,
    `https://www.meetup.com/frontendisti-brno/events/`,
    `https://www.meetup.com/frontendisti/events/`,
    `https://www.meetup.com/Brno-Fullstack-Developers/`,
    `https://www.meetup.com/Brno-Java-Meetup`,
    `https://www.meetup.com/Brno-Distributed-Systems-Meetup-Group/`,
    `https://www.meetup.com/WrikeTechClub/`,
    `https://www.meetup.com/ZEIT-Czech-Community/`,
    `https://www.facebook.com/groups/684672464913744/events` /* PRÁCE - PROGRAMÁTOŘI, VÝVOJÁŘI, KODÉŘI - PRÁCE A BRIGÁDY V OBLASTI IT */,
    `https://www.facebook.com/sitport/events/`,
    `https://www.facebook.com/ceehacks/events/`,
    `https://www.facebook.com/codekiwicom/events/`,
    `https://www.facebook.com/groups/1630097043923905/events` /* IT akce v Brně */,
    `https://www.facebook.com/groups/236797913757886/events` /* IT akce v Praze */,
    `https://www.facebook.com/pg/codekiwicom/events/`,
    `https://www.facebook.com/pg/navolnenoze/events/`,
    `https://www.facebook.com/impacthubbrno/events/`,
    `https://www.facebook.com/pg/strvcom/events/`,
    `https://www.facebook.com/pg/itnetworkcz/events/`,
    `https://www.facebook.com/pg/barcampkolin/events/`,
    `https://www.facebook.com/pg/plzenskybarcamp/events/`,
    `https://www.meetup.com/pro/machine-learning-meetups`,
    `https://www.facebook.com/pg/barcamp.brno/events/`,
    `https://www.facebook.com/pg/prazskybarcamp/events/`,
    `https://www.facebook.com/pg/barcamphradec/events/`,
    `https://www.facebook.com/groups/frontendisti/events/` /* Frontendisti.cz */,
    `https://www.facebook.com/pg/jobsdevcz/events/`,
    `https://www.facebook.com/pg/nettefwpivo/events/`,
    `https://www.facebook.com/pg/FreeloCZ/events/`,
    `https://www.facebook.com/pg/Backendisti/events/`,
    `https://www.facebook.com/pg/asociaceux/events/`,
    `https://www.facebook.com/pg/DevConf.cz/events/`,
    `https://www.facebook.com/pg/XMLPragueConference/events/`,
    `https://www.facebook.com/pg/OpenAlt/events/`,
    `https://www.facebook.com/pg/linuxdays/events/`,
    `https://www.facebook.com/pg/avrar.cz/events/`,
    `https://www.facebook.com/pg/mdevtalk/events/`,
    `https://www.facebook.com/pg/topmonks/events/`,
    `https://www.facebook.com/pg/vejdiven/events/`,
    `https://www.facebook.com/pg/StartupWiseGuys/events/`,
    `https://www.facebook.com/pg/czkug/events/`,
    `https://www.facebook.com/pg/Vue-Prague-107825407399197/events/`,
    `https://www.facebook.com/pg/disrupthrprague/events/`,
    `https://www.facebook.com/pg/impacthubpraha/events/`,
    `https://www.facebook.com/pg/aimtecCZ/events/`,
    `https://www.eventbrite.com/o/wrike-tech-club-27552199725`,
    `https://www.facebook.com/MeasurecampCZ/events`,
    `https://www.facebook.com/linuxdays/events`,
    `https://www.facebook.com/FUNprague/events`,
];
